---
- name: server
  hosts: localhost
  vars_files:
     - 'vars.yml'
  remote_user: root
  become: yes
  roles:
    - mc
  tasks:
     - name: print secure variable
       debug: msg="my secure variable '{{ my_secure_variable }}'"`
